name: Validate Data

on:
  push:
  pull_request:

jobs:
  validate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Notion Card Creator
        uses: wcchristian/gh-action-notion-card@v1.0.0
